### ISSUE TITLE
SubPageLink to "Journal Line No." instead of "Line No."

### ISSUE THREAD

**Issue by StefanBRAG** [document-capture/OPplus-payment-proposal-preview#1]
https://github.com/document-capture/OPplus-payment-proposal-preview/blob/56f4affe6d94080381c9d93bdf65d24717d9bcc8/objects/1.0.1.0/BC19-DC8/src/pageextension/PTEDCPaymPropLinePrev.PageExt.al#L12

SubPageLink = "Journal Template Name" = field("Journal Template Name"),
                              "Journal Batch Name" = field("Journal Batch Name"),
                              **"Journal Line No." = field("Journal Line No.");**
                              //"Line No." = field("Line No.");

**Comment by sradloff** [comment]
Fixed, actually we need the new and the commented line.
I just commited the changes.
